version: '3.7'
services:
  intellisense-test-service:
    image: intellisense-test-service:v1
    ports:
      - "8002:8002"
    restart: always
    networks:
      - springcloud
networks:
  springcloud: